
name: Java pipeline

on:
  push:
    branches: [ java ]
  pull_request:
    branches: [ java ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: List
      run: |
        ls 
        pwd
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        

    - name: Cache Maven packages
      uses: actions/cache@v1

      with:
          ref: java
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
          
          
    - name: Build with Maven
      run: |
           mvn --batch-mode --update-snapshots verify
           
    - name: API call
      run: curl --location --request GET 'https://madhuryaramesh.atlassian.net/rest/api/3/workflow' --header 'Authorization: Basic bWFkaHVyeWEucnMxQGdtYWlsLmNvbTpRUFVjVGpuTTRBRTRGUlZsUWpTZzk5RjU=' 
           
           
        
      
    - name: List
      run: |
        ls 
        pwd
          
 
      
         
        
   
        
   


































          

          

          

          
    
    
        
     
